'use client'
import type { Metadata } from 'next';
import Link from 'next/link';
import { billSVG, burgerSVG, calendarSVG, heartBoxSVG, logoutSVG, profileSVG, starSVG } from '@/helpers/svg';
import Button from '@/components/Button';
import MenuList from '@/components/MenuList';
import Dropdown from '@/components/Dropdown';
import { removeToken } from '@/helpers/auth/logout';
import { useRouter } from 'next/navigation';
import { useDispatch } from 'react-redux';
import { clearCurrentAccount } from '@/redux/features/auth-slice';

export const metadata: Metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
};

export default function Template({
  children,
}: {
  children: React.ReactNode;
}) {

    const dispatch = useDispatch()
    const router = useRouter();

    function handleLogout() {
        removeToken()
        dispatch(clearCurrentAccount())
        router.push('/')
    }

  return (
    <div>
        <div className="navbar bg-base-100 border-b-2 relative z-10">
            <div className="flex-1">
                <Link className="btn btn-ghost text-xl" href={'/homepage'}>Website</Link>
            </div>
            <Dropdown className='dropdown-end' buttonSvg={burgerSVG} ulClassName='flex gap-4'>
                <MenuList redirect='/dashboard/user/' svg={calendarSVG} text={''}>Upcoming Events</MenuList>
                <MenuList redirect='' svg={billSVG} text={''}>Transaction</MenuList>
                <MenuList redirect='' svg={starSVG} text={''}>Review</MenuList>
                <MenuList redirect='' svg={heartBoxSVG} text={''}>Wishlist</MenuList>
                <Button className="" text="Account" svg={profileSVG} redirect=''>
                    Account
                </Button>
                <Button optionalFunc={handleLogout} className="bg-slate-800 text-slate-50 hover:text-slate-800" text="Logout" svg={logoutSVG} redirect='' >
                    Logout
                </Button>
            </Dropdown>
        </div>
        { children }
    </div>
  );
}
